import type { ICampaign, ICampaignListPayload } from "@/entities/campaign/model/campaign.types.ts";

export const mockCampaigns: ICampaign[] = [
  // INSTAGRAM
  {
    campaignId: "cmp-inst-1",
    socialMedia: "instagram",
    campaignName: "IG Promo Campaign",
    creatorRole: "client",
    creatorName: "John Doe",
    followers: 120000,
    cost: 500,
    salePrice: 700,
    publicPrice: 900,
    createdAt: "22.10.2025",
    status: "proposal",
    statusLabel: "Proposal Sent",
    reportSent: false,
    paymentStatus: "wait",
    invoiceId: "inv-inst-1",
    shortInvoiceId: "I001",
    notes: "Initial proposal",
    affiliatePartner: "Partner A",
    affiliateCommission: "10%",
    affiliatePaid: 10000,
  },
  {
    campaignId: "cmp-inst-2",
    socialMedia: "instagram",
    campaignName: "IG Promo Campaign",
    creatorRole: "client",
    creatorName: "John Doe",
    followers: 120000,
    cost: 500,
    salePrice: 700,
    publicPrice: 900,
    createdAt: "22.10.2025",
    status: "pending",
    statusLabel: "Waiting Approval",
    reportSent: false,
    paymentStatus: "wait",
    invoiceId: "inv-inst-2",
    shortInvoiceId: "I002",
    notes: "Pending client approval",
    affiliatePartner: "Partner A",
    affiliateCommission: "50% profits",
    affiliatePaid: 20000,
  },
  {
    campaignId: "cmp-inst-3",
    socialMedia: "instagram",
    campaignName: "IG Promo Campaign",
    creatorRole: "client",
    creatorName: "John Doe",
    followers: 120000,
    cost: 500,
    salePrice: 700,
    publicPrice: 900,
    createdAt: "27.03.2026",
    status: "distributing",
    statusLabel: "In Progress",
    reportSent: false,
    paymentStatus: "paid",
    invoiceId: "inv-inst-3",
    shortInvoiceId: "I003",
    notes: "Campaign running",
    affiliatePartner: "Partner A",
    affiliateCommission: "50% profits",
    affiliatePaid: 10000,
  },
  {
    campaignId: "cmp-inst-4",
    socialMedia: "instagram",
    campaignName: "IG Promo Campaign",
    creatorRole: "client",
    creatorName: "John Doe",
    followers: 120000,
    cost: 500,
    salePrice: 700,
    publicPrice: 900,
    createdAt: "27.03.2026",
    status: "completed",
    statusLabel: "Completed",
    reportSent: true,
    paymentStatus: "paid",
    invoiceId: "inv-inst-4",
    shortInvoiceId: "I004",
    notes: "Finished successfully",
    affiliatePartner: "Partner A",
    affiliateCommission: "50% profits",
    affiliatePaid: 10000,
  },

  // TIKTOK
  {
    campaignId: "cmp-tt-1",
    socialMedia: "tiktok",
    campaignName: "TikTok Viral Boost",
    creatorRole: "client",
    creatorName: "Alice Smith",
    followers: 80000,
    cost: 300,
    salePrice: 450,
    publicPrice: 600,
    createdAt: "27.03.2026",
    status: "proposal",
    statusLabel: "Proposal Sent",
    reportSent: false,
    paymentStatus: "wait",
    invoiceId: "inv-tt-1",
    shortInvoiceId: "T001",
    notes: "Proposal stage",
    affiliatePartner: "Partner B",
    affiliateCommission: "15% profits",
    affiliatePaid: 10000,
  },

  // YOUTUBE
  {
    campaignId: "cmp-yt-1",
    socialMedia: "youtube",
    campaignName: "YouTube Review Campaign",
    creatorRole: "client",
    creatorName: "Mike Johnson",
    followers: 250000,
    cost: 1200,
    salePrice: 1500,
    publicPrice: 1800,
    createdAt: "27.03.2026",
    status: "pending",
    statusLabel: "Waiting Approval",
    reportSent: false,
    paymentStatus: "wait",
    invoiceId: "inv-yt-1",
    shortInvoiceId: "Y001",
    notes: "Waiting confirmation",
    affiliatePartner: "Partner C",
    affiliateCommission: "12%",
    affiliatePaid: 10000,
  },

  // FACEBOOK
  {
    campaignId: "cmp-fb-1",
    socialMedia: "facebook",
    campaignName: "FB Ads Push",
    creatorRole: "client",
    creatorName: "Emma Brown",
    followers: 60000,
    cost: 200,
    salePrice: 350,
    publicPrice: 500,
    createdAt: "27.03.2026",
    status: "distributing",
    statusLabel: "In Progress",
    reportSent: false,
    paymentStatus: "paid",
    invoiceId: "inv-fb-1",
    shortInvoiceId: "F001",
    notes: "Ads running",
    affiliatePartner: "Partner D",
    affiliateCommission: "8% profits",
    affiliatePaid: 10000,
  },

  // SPOTIFY
  {
    campaignId: "cmp-sp-1",
    socialMedia: "spotify",
    campaignName: "Spotify Playlist Boost",
    creatorRole: "client",
    creatorName: "DJ Nova",
    followers: 150000,
    cost: 700,
    salePrice: 900,
    publicPrice: 1200,
    createdAt: "27.03.2026",
    status: "completed",
    statusLabel: "Completed",
    reportSent: true,
    paymentStatus: "paid",
    invoiceId: "inv-sp-1",
    shortInvoiceId: "S001",
    notes: "Playlist campaign done",
    affiliatePartner: "Partner E",
    affiliateCommission: "10%",
    affiliatePaid: 10000,
  },

  // SOUNDCLOUD
  {
    campaignId: "cmp-sc-1",
    socialMedia: "soundcloud",
    campaignName: "SoundCloud Boost",
    creatorRole: "client",
    creatorName: "BeatMaker",
    followers: 40000,
    cost: 150,
    salePrice: 250,
    publicPrice: 350,
    createdAt: "27.03.2026",
    status: "proposal",
    statusLabel: "Proposal Sent",
    reportSent: false,
    paymentStatus: "wait",
    invoiceId: "inv-sc-1",
    shortInvoiceId: "SC01",
    notes: "New proposal",
    affiliatePartner: "Partner F",
    affiliateCommission: "5% profits",
    affiliatePaid: 35000,
  },

  // PRESS
  {
    campaignId: "cmp-pr-1",
    socialMedia: "press",
    campaignName: "Press Coverage Campaign",
    creatorRole: "client",
    creatorName: "Label X",
    followers: 0,
    cost: 1000,
    salePrice: 1300,
    publicPrice: 1600,
    createdAt: "27.03.2026",
    status: "pending",
    statusLabel: "Waiting Approval",
    reportSent: false,
    paymentStatus: "wait",
    invoiceId: "inv-pr-1",
    shortInvoiceId: "P001",
    notes: "Press outreach",
    affiliatePartner: "Partner G",
    affiliateCommission: "20%",
    affiliatePaid: 1500,
  },

  // MULTIPROMO
  {
    campaignId: "cmp-mp-1",
    socialMedia: "multipromo",
    campaignName: "Multi Channel Campaign",
    creatorRole: "client",
    creatorName: "Agency Pro",
    followers: 500000,
    cost: 2000,
    salePrice: 2500,
    publicPrice: 3000,
    createdAt: "27.03.2026",
    status: "completed",
    statusLabel: "Completed",
    reportSent: true,
    paymentStatus: "paid",
    invoiceId: "inv-mp-1",
    shortInvoiceId: "M001",
    notes: "All channels done",
    affiliatePartner: "Partner H",
    affiliateCommission: "15% profits",
    affiliatePaid: 876,
  },
];

export const getCampaigns = async (): Promise<ICampaignListPayload> => {
  return Promise.resolve({
    items: mockCampaigns,
    total: 2,
    page: 1,
    limit: 20,
    totalPages: 1,
  });
};
